service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  simpleLamdas:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

  wlcLamdas:
    handler: handler.wlc
    events:
      - http:
          path: /welcome
          method: post
  list:
    handler: books/list.handler
    events:
      - http:
          path: /book-list/
          method: get
  getBooks:
    handler: books/get.handler
    events:
      - http:
          path: /book/{id}
          method: get
  create:
    handler: books/create.handler
    events:
      - http:
          path: /books
          method: post
  update:
    handler: books/update.handler
    events:
      - http:
          path: /book/{id}
          method: put
  deleteBooks:
    handler: books/delete.handler
    events:
      - http:
          path: /book
          method: delete